from typing import TypedDict


class TripState(TypedDict):
    raw_messages: list[dict]          # Full conversation history collected by N1.
    constraints: dict                 # Structured trip constraints: start_location, duration_hours, group_size, vehicle, interests, budget_feel.
    clarification_round: int          # Number of clarification question rounds already used by N1.

    isochrone_polygon: dict           # GeoJSON polygon representing the reachable area from the start location.
    candidates: list[dict]            # Top 20 raw candidate destinations with coordinates, tags, distance, and ranking metadata.
    candidate_index: int              # Raw candidate cursor currently being validated.

    validated_candidates: list[dict]  # Destinations confirmed usable after access, hours, and travel-time checks.
    presented_candidate_index: int    # Index of the validated candidate currently shown to the user.
    validated_destination: dict       # Current validated destination shown to the user.
    validation_failures: list[str]    # Diagnostic reasons raw destination candidates were rejected.

    user_confirmed: bool              # True when the user accepts the destination; False when they request another option.

    route: dict                       # Full route data: GeoJSON route line, ordered waypoints, distances, legs, and ETAs.
    food_stops: list[dict]            # Validated restaurant or cafe stops selected along the route.
    food_availability: list[dict]     # Meal decisions: eat at destination, route options, eat at home, or carry/parcel guidance.

    itinerary_draft: str              # Human-readable itinerary prose generated by N6 with inline self-check.

    claim_failures: list[dict]        # Structured output validation issues from N5, shaped like {"field": ..., "issue": ..., "severity": ...}.
    route_attempt_count: int          # Number of times N5 has routed back to N4 with a different destination due to validation errors.
    rewrite_count: int                # Deprecated; retained for schema compatibility.

    final_geojson: dict               # Final FeatureCollection consumed by the Mapbox/pydeck renderer.
    final_itinerary: str              # Final validated itinerary prose shown to the user.
    timeline: list[dict]              # Ordered timeline entries: time, label, coords, type, and notes.
