from typing import TypedDict


class TripState(TypedDict):
    raw_messages: list[dict]          # Full conversation history collected by N1.
    constraints: dict                 # Structured trip constraints: start_location, duration_hours, group_size, vehicle, interests, budget_feel.
    clarification_round: int          # Number of clarification question rounds already used by N1.
    clarification_prompt: dict        # Structured options for the current N1 question: {question, input_type, options, allow_custom}. input_type is one of single_select, multi_select, text.

    isochrone_polygon: dict           # GeoJSON polygon representing the reachable area from the start location.
    candidates: list[dict]            # Top 20 raw candidate destinations with coordinates, tags, distance, and ranking metadata.
    candidate_index: int              # Raw candidate cursor currently being validated.

    validated_candidates: list[dict]  # Destinations confirmed usable after access, hours, and travel-time checks (the selectable queue).
    presented_candidate_indices: list[int]  # Indices of validated candidates already shown to the user.
    selected_destinations: list[dict] # The 1-3 destinations the user picked from the queue and confirmed.
    max_destinations: int             # Maximum stops the user may select. Default 3.
    removal_notice: str               # User-facing message when N5 drops a selected destination it could not plan.
    validation_failures: list[str]    # Diagnostic reasons raw destination candidates were rejected.

    user_confirmed: bool              # True when the user confirms their selection; False when a re-selection is needed.

    route: dict                       # Full route data: GeoJSON route line, ordered waypoints, distances, legs, and ETAs.
    food_stops: list[dict]            # Validated restaurant or cafe stops selected along the route.
    food_availability: list[dict]     # Meal decisions: eat at destination, route options, eat at home, or carry/parcel guidance.

    itinerary_draft: str              # Human-readable itinerary prose generated by N6 with inline self-check.

    claim_failures: list[dict]        # Structured output validation issues from N5, shaped like {"field": ..., "issue": ..., "severity": ...}.
    route_attempt_count: int          # Number of times N5 has routed back to N4 with a different destination due to validation errors.
    rewrite_count: int                # Deprecated; retained for schema compatibility.

    final_geojson: dict               # Final FeatureCollection consumed by the Mapbox/pydeck renderer.
    final_itinerary: str              # Final validated itinerary prose shown to the user.
    timeline: list[dict]              # Ordered timeline entries: time, label, coords, type, and notes.
