from typing import TypedDict


class TripState(TypedDict):
    raw_messages: list[dict]          # Full conversation history collected by N1.
    constraints: dict                 # Structured trip constraints: start_location, duration_hours, group_size, vehicle, interests, budget_feel.
    clarification_round: int          # Number of clarification question rounds already used by N1.

    isochrone_polygon: dict           # GeoJSON polygon representing the reachable area from the start location.
    candidates: list[dict]            # Top 5 candidate destinations with coordinates, tags, distance, and ranking metadata.
    candidate_index: int              # Index of the candidate currently being validated or presented.

    validated_destination: dict       # Destination confirmed usable after access, hours, and travel-time checks.
    validation_failures: list[str]    # Reasons previous destination candidates were rejected.

    user_confirmed: bool              # True when the user accepts the destination; False when they request another option.

    route: dict                       # Full route data: GeoJSON route line, ordered waypoints, distances, legs, and ETAs.
    food_stops: list[dict]            # Validated restaurant or cafe stops selected along the route.

    itinerary_draft: str              # Human-readable itinerary prose generated by N5 before claim validation.

    claim_failures: list[dict]        # Claim validation failures, shaped like {"claim": ..., "reason": ...}.
    rewrite_count: int                # Number of times the itinerary composer has been re-run after validation failures.

    final_geojson: dict               # Final FeatureCollection consumed by the Mapbox/pydeck renderer.
    final_itinerary: str              # Final validated itinerary prose shown to the user.
    timeline: list[dict]              # Ordered timeline entries: time, label, coords, type, and notes.
